quarkus.live-reload.instrumentation=true
quarkus.http.body.handle-file-uploads=true
quarkus.http.body.delete-uploaded-files-on-end=false
quarkus.http.enable-compression=true
quarkus.http.body.uploads-directory=store/temp
quarkus.http.limits.max-form-attribute-size=50M
quarkus.log.level=DEBUG
quarkus.console.color=true
quarkus.log.category."com.hangout.core".level=DEBUG
quarkus.log.category."com.hangout.core".min-level=TRACE
quarkus.stork.hangout-storage-service.service-discovery.type=eureka
quarkus.stork.hangout-storage-service.service-discovery.eureka-host=localhost
quarkus.stork.hangout-storage-service.service-discovery.eureka-port=8761
