application:
  name: 
  
kafka:
  url:
  topic:
  group-id:

aws:
  region: 
s3:
  upload-bucket: 
  storage-bucket: 

datasource:
  username:
  dbname:

log:
  level:

process:
    queue-length:
    pool-strength:

otel:
  endpoint: