kafka:
  host: localhost
  port: 9092
  topic: content
  group-id: hangout-storage-service

log:
  level: debug
  backend: zerolog

minio:
    base-url: localhost:9000
    access-key: vLmiqXs8DUB2jwocd14W
    secret-key: mK5ByFQJKbm2nsjBvyLmkggITrP0sdfSPbspvr45
    upload-bucket: hangout-upload-path
    storage-bucket: hangout-storage-path
    
process:
    queue-length: 100
    pool-strength: 4