kafka:
  url: localhost:9092
  topic: content
  group-id: hangout-storage-service

log:
  level: debug
  backend: zerolog

minio:
    base-url: localhost:9000
    access-key: ITtpzgn9Q0UjIbi0D71V
    secret-key: ukUq1HHBUrjBXMEaTt55CilhNvvvEicnjT3SSqwH
    upload-bucket: upload
    storage-bucket: processed
    
process:
    queue-length: 4
    pool-strength: 4

datasource:
  username: postgres
  password: PkNLm@#2357
  url: localhost:5432
  dbname: posts