application:
  name: hangout-storage-service
  
kafka:
  url: localhost:9092
  topic: content
  group-id: hangout-storage-service

log:
  level: debug

minio:
    base-url: localhost:9000
    upload-bucket: upload
    storage-bucket: processed
    
process:
    queue-length: 4
    pool-strength: 4

datasource:
  username: postgres
  dbname: posts

otel:
  endpoint: localhost:4317