kafka:
  host: localhost
  port: 9092
  topic: content
  group-id: hangout-storage-service

log:
  level: debug
  backend: zerolog

hangout:
  media:
    upload-path: /media/soumalya/793f3da3-8908-48a8-a4ce-a638275951fa/hangout-upload-path
    processed-path: /media/soumalya/793f3da3-8908-48a8-a4ce-a638275951fa/hangout-processed-path
    queue-length: 100
  worker-pool:
    strength: 4
  
