kafka:
  host: localhost
  port: 9092
  topic: content
  group-id: hangout-storage-service

log:
  level: debug
  backend: zerolog

path:
    upload: /media/soumalya/793f3da3-8908-48a8-a4ce-a638275951fa/hangout-upload-path
    storage: /media/soumalya/793f3da3-8908-48a8-a4ce-a638275951fa/hangout-storage-path
    
process:
    queue-length: 100
    pool-strength: 4